spring:
  application:
    name: stockox-user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/stockox_users_dev}
    username: ${SPRING_DATASOURCE_USERNAME:stockox_user}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 20
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  mail:
    host: ${MAIL_HOST:smtp.zoho.in}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:stockoxindia@zohomail.in}
    password: ${MAIL_PASSWORD:3dURiNv0zR9u}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          from: ${MAIL_USERNAME:stockoxindia@zohomail.in}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      repositories:
        enabled: false

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  health:
    mail:
      enabled: false
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    com.stockox: INFO
    org.springframework.mail: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:ImsSecretKey2024!ChangeThisInProductionMin32Chars}
    access-expiry-ms: 900000
    refresh-expiry-ms: 604800000
  otp:
    expiry-minutes: 10
    length: 6
    max-attempts: 5
  app-name: "StockOx"
  frontend-url: ${FRONTEND_URL:http://localhost:3000}