spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/stockox_users_dev}
    username: ${SPRING_DATASOURCE_USERNAME:stockox_user}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

app:
  jwt:
    secret: ${JWT_SECRET:ImsSecretKey2024!ChangeThisInProductionMin32Chars}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

server:
  port: 8081